#!/usr/bin/env python3
"""Emit paper/generated/macros.tex from derived files. Never invent a number."""
from __future__ import annotations

import json
import math
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from analysis.lib.constants import DATA_DERIVED, DATA_SAMPLES, PAPER_GEN, UNAVAIL  # noqa: E402

UNAVAIL_MACRO = r"\textbf{UNAVAILABLE}"


def loadj(name: str) -> dict | None:
    p = DATA_DERIVED / name
    if not p.exists():
        return None
    return json.loads(p.read_text())


def pct(x) -> str:
    if x is None or (isinstance(x, float) and not math.isfinite(x)):
        return UNAVAIL_MACRO
    return f"{100.0 * float(x):.1f}\\%"


def ratio(k, n) -> str:
    if k is None or n is None:
        return UNAVAIL_MACRO
    return f"{int(k)}/{int(n)}"


def fmt_p(p) -> str:
    if p is None or (isinstance(p, float) and not math.isfinite(p)):
        return UNAVAIL_MACRO
    if p < 0.001:
        return "$p<0.001$"
    return f"$p={p:.3f}$"


def macro(name: str, value: str) -> str:
    return f"\\newcommand{{\\{name}}}{{{value}}}\n"


def main() -> None:
    PAPER_GEN.mkdir(parents=True, exist_ok=True)
    lines = [
        "% Auto-generated by analysis/emit_macros.py. Do not edit.\n",
        "% Missing computations become \\textbf{UNAVAILABLE}, never a guessed number.\n",
    ]
    defs: dict[str, str] = {}

    open_share = loadj("wp1_open_share.json")
    if open_share:
        defs["OpenShare"] = pct(open_share["rate"])
        defs["OpenShareFrac"] = ratio(open_share["k"], open_share["n"])
        defs["OpenShareCI"] = f"{100*open_share['ci_low']:.1f}--{100*open_share['ci_high']:.1f}"
    else:
        defs["OpenShare"] = UNAVAIL_MACRO
        defs["OpenShareFrac"] = UNAVAIL_MACRO
        defs["OpenShareCI"] = UNAVAIL_MACRO

    hl = loadj("wp1_headline.json")
    defs["HeadlineTreatment"] = hl["headline_treatment"] if hl else UNAVAIL_MACRO

    prev = DATA_DERIVED / "wp1_prevalence.csv"
    if prev.exists():
        import pandas as pd

        df = pd.read_csv(prev)
        for _, r in df.iterrows():
            t = r["treatment"]
            defs[f"PrShare{t}"] = pct(r["pr_share"])
            defs[f"RepoShareAll{t}"] = pct(r["repo_share_all"])
            defs[f"RepoShareGeTwo{t}"] = pct(r["repo_share_ge2"])
            defs[f"NPairs{t}"] = str(int(r["n_pairs"]))
            defs[f"NCrossPairs{t}"] = str(int(r["n_cross_pairs"]))

    uni = DATA_SAMPLES / "universe_counts.json"
    if uni.exists():
        u = json.loads(uni.read_text())
        defs["NReposIntra"] = str(u.get("n_repos_intra", UNAVAIL_MACRO))
        defs["NReposCross"] = str(u.get("n_repos_cross", UNAVAIL_MACRO))
        defs["NReposMatched"] = str(u.get("n_repos_matched", UNAVAIL_MACRO))
        defs["NReplayCandidates"] = str(u.get("n_replay_candidates", UNAVAIL_MACRO))

    av = loadj("legacy_availability.json")
    if av:
        defs["LegacyAttempted"] = str(av["attempted"])
        defs["LegacyEvaluable"] = str(av["evaluable"])
    rates = DATA_DERIVED / "legacy_rates.csv"
    if rates.exists():
        import pandas as pd

        df = pd.read_csv(rates)
        for _, r in df.iterrows():
            if r["label"] == "same":
                defs["LegacyIntraRate"] = pct(r["rate"])
                defs["LegacyIntraFrac"] = ratio(r["conflicts"], r["evaluable"])
                defs["LegacyIntraCI"] = f"{100*r['ci_low']:.1f}--{100*r['ci_high']:.1f}"
            if r["label"] == "cross":
                defs["LegacyCrossRate"] = pct(r["rate"])
                defs["LegacyCrossFrac"] = ratio(r["conflicts"], r["evaluable"])
                defs["LegacyCrossCI"] = f"{100*r['ci_low']:.1f}--{100*r['ci_high']:.1f}"

    matched = loadj("legacy_matched.json")
    if matched and isinstance(matched.get("mcnemar"), dict):
        defs["LegacySharedEval"] = str(matched["n_shared_evaluable"])
        defs["LegacyMcNemarP"] = fmt_p(matched["mcnemar"].get("p"))
        defs["LegacyCrossOnly"] = str(matched["cross_only_conflict"])
        defs["LegacyIntraOnly"] = str(matched["intra_only_conflict"])
        ir = matched.get("intra_rate") or {}
        cr = matched.get("cross_rate") or {}
        defs["LegacyMatchedIntra"] = pct(ir.get("rate"))
        defs["LegacyMatchedCross"] = pct(cr.get("rate"))

    comp = loadj("legacy_composition.json")
    if comp:
        defs["LegacyExpectedCross"] = pct(comp.get("expected_rate_mean"))
        defs["LegacyObservedCross"] = pct(comp.get("observed_rate"))

    mv = loadj("legacy_multivendor_intra.json")
    if mv and isinstance(mv.get("fisher"), dict):
        defs["LegacyFisherP"] = fmt_p(mv["fisher"].get("p"))
        defs["LegacyMultiIntra"] = pct((mv.get("multi_rate") or {}).get("rate"))
        defs["LegacySingleIntra"] = pct((mv.get("single_rate") or {}).get("rate"))
        defs["LegacyMultiFrac"] = ratio(mv.get("multi_k"), mv.get("multi_n"))
        defs["LegacySingleFrac"] = ratio(mv.get("single_k"), mv.get("single_n"))

    tax = loadj("legacy_taxonomy_totals.json")
    if tax:
        defs["LegacyConfPairs"] = str(tax["n_conflicting_pairs"])
        defs["LegacyConfFiles"] = str(tax["n_conflicted_files"])
        defs["LegacyTypeSignals"] = str(tax["n_type_signals"])
    taxcsv = DATA_DERIVED / "legacy_taxonomy.csv"
    if taxcsv.exists():
        import pandas as pd

        tdf = pd.read_csv(taxcsv)
        for _, r in tdf.iterrows():
            if r["kind"] == "type_group" and r["name"] == "structural":
                defs["LegacyStructural"] = pct(r["pct"])
            if r["kind"] == "type_group" and r["name"] == "content":
                defs["LegacyContent"] = pct(r["pct"])
            if r["kind"] == "conflict_type" and r["name"] == "modify/delete":
                defs["LegacyModDel"] = pct(r["pct"])
            if r["kind"] == "conflict_type" and r["name"] == "add/add":
                defs["LegacyAddAdd"] = pct(r["pct"])
            if r["kind"] == "file_category" and r["name"] == "Source Code":
                defs["LegacySrcFiles"] = pct(r["pct"])

    dur = loadj("wp1_overlap_duration_B.json") or loadj("wp1_overlap_duration_A.json")
    if dur:
        defs["OverlapMeanHours"] = f"{dur['mean_hours']:.1f}"
        defs["OverlapShare1h"] = pct(dur.get("share_lt_1h"))
        defs["OverlapShare24h"] = pct(dur.get("share_lt_24h"))

    cx = loadj("wp1_cross_pair_share.json")
    if cx:
        defs["CrossPairShare"] = pct(cx.get("share"))
        defs["CrossPairN"] = str(int(cx["n_cross"])) if cx.get("n_cross") is not None else UNAVAIL_MACRO
        defs["CrossPairDenom"] = str(int(cx["n_pairs"])) if cx.get("n_pairs") is not None else UNAVAIL_MACRO

    agentcsv = DATA_DERIVED / "legacy_agent_intra.csv"
    if agentcsv.exists():
        import pandas as pd

        adf = pd.read_csv(agentcsv)
        for _, r in adf.iterrows():
            key = str(r["agent"]).replace("_", "")
            defs[f"AgentIntra{key}"] = pct(r["rate"])
            defs[f"AgentIntra{key}Frac"] = ratio(r["conflicts"], r["evaluable"])

    snap = loadj("snapshot.json")
    if snap:
        defs["NPopPRs"] = str(snap.get("n_pull_requests", UNAVAIL_MACRO))
        defs["NPopRepos"] = str(snap.get("n_repositories", UNAVAIL_MACRO))

    for name, texname in (
        ("wp3_status.json", "WPThreeStatus"),
        ("wp4_status.json", "WPFourStatus"),
        ("wp5_status.json", "WPFiveStatus"),
        ("wp6_status.json", "WPSixStatus"),
    ):
        st = loadj(name)
        defs[texname] = (st or {}).get("status", UNAVAIL)

    for k, v in defs.items():
        lines.append(macro(k, v if v is not None else UNAVAIL_MACRO))

    (PAPER_GEN / "macros.tex").write_text("".join(lines))
    print(f"wrote {PAPER_GEN / 'macros.tex'} ({len(defs)} macros)")


if __name__ == "__main__":
    main()
